# LOCAL_CHROME  REMOTE_CHROME LOCAL_FIREFOX

driver:
  type: LOCAL_CHROME

#webdriver:
#  chrome_driver_path: D:/project/selenium/chromedriver/v2.9/chromedriver.exe
#  gecko_driver_path: D:/project/selenium/firefox/v18/geckodriver.exe
#  firefox_bin_path: D:/program/Mozilla Firefox/firefox.exe

log:
  fommat: '%(asctime)s %(levelname)-8s %(filename)s[line:%(lineno)d] - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

  console:
    level: INFO

  file:
    level: DEBUG
    path: ../log/myapp.log